apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: welcome-banner
spec:
  backgroundColor: '#880000'
  color: '#fff'
  link:
    href: https://www.redhat.com/en/summit
    text: (Event Information)
  location: BannerTop
  text: Bienvenidos al Red Hat Summit 2024!
